# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath C:/modeltech64_10.5/win64
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.cache/wt [current_project]
set_property parent.project_path D:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/2017FPGA/ZYNQ_car/SmartCar_IP [current_project]
set_property ip_output_repo d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/hdl/system_wrapper.v
add_files D:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0_1/system_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0_1/system_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0_1/system_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_optical_0_1/system_optical_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_optical_0_1/system_optical_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_optical_0_1/system_optical_0.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_0_1/system_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_0_1/system_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_0_1/system_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_xbar_0_1/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_auto_pc_6_1/system_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_auto_pc_5_1/system_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_auto_pc_4_1/system_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_auto_pc_3_1/system_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_auto_pc_2_1/system_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_auto_pc_1_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_auto_pc_0_1/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/ip/system_auto_pc_7_1/system_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files D:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/sources_1/bd/system/system.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/constrs_1/new/zynq_car.xdc
set_property used_in_implementation false [get_files D:/2017FPGA/ZYNQ_car/ZYNQ_car/ZYNQ_car.srcs/constrs_1/new/zynq_car.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef system_wrapper.dcp

catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
